### ISSUE TITLE
search autocomplete is no longer working

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-portal#179]
When attempting to search for an individual on the profiles app, the dropdown does not appear.

**Comment by guylepage3** [comment]
@shea256 @larrysalibra 

I am going to need your assistance with this issue. There are connection errors for search queries in the profiles app when attempting to lookup a user.

<img width="587" alt="screenshot 2017-02-06 14 19 32" src="https://cloud.githubusercontent.com/assets/1711854/22662600/9c6d9640-ec77-11e6-81a6-dd8db45519e0.png">

**Comment by larrysalibra** [comment]
@guylepage3 the connection error is because your mock core server isn't running. it should start up automatically if you have `blockstack` on your `PATH` and working 

See instructions here: https://github.com/blockstack/blockstack-browser/tree/web-mock-core#developing-locally

You can see why it isn't starting by running `./node_modules/.bin/gulp mockCore`

**Comment by larrysalibra** [comment]
The other reason this doesn't work is that the "search for people" "search" box is actually the old address bar component from when this was a "real" browser. We'll need to modify it to have this behavior.

**Comment by guylepage3** [comment]
resolved by @shea256. closing issue
