### ISSUE TITLE
macOS: ID Pending after >200 Blocks - Missing Transfer Step

### ISSUE THREAD

**Issue by danielmcclure** [blockstack/blockstack-portal#365]
Attempted to register an ID through macOS desktop GUI however it is still pending days later after over 200 blocks. 

The ID appears in the Blockstack explorer but only has: PreOrder, Registration and Update stages referenced.

Inside the localhost GUI it states pending and the profile as not found if you click to view publicly.

CC: @larrysalibra

**Comment by muneeb-ali** [comment]
Thanks for reporting @danielmcclure! 

@larrysalibra this looks like a Core issue to me. What we need to know is the state of the queues on the local daemon and why the transfer didn't go out i.e., is the local daemon still running, if yes, what's the state it is in.

**Comment by larrysalibra** [comment]
Thanks so much for sharing this @danielmcclure !

I'm going to give you instructions to check if your Core node is still running if the name transfer is still in queue.

You'll need to first get your Core wallet password (which also doubles as an API password).

You can find this in macOS's Keychain Services app.

Search for `blockstack-core` and the entry should appear as in the screenshot below:

<img width="586" alt="screen shot 2017-04-01 at 4 16 38 am" src="https://cloud.githubusercontent.com/assets/597182/24567869/16e1a1c0-1692-11e7-88d3-41bcbbba54cc.png">

Make a note of the password. (You'll be able to use this later on the command line to recover your name)

Next, run the following command in Terminal, replacing `<CORE-PASS>` with the password you just recovered.

`curl -H "Authorization: basic <CORE-PASS>" http://localhost:6270/v1/node/registrar/state`

If your transaction queue is empty ( @jcnelson please correct me if I'm wrong), it will return an empty array: `[]`

This also means your Core node is still running. (good news!)

Otherwise, it will provide some information about what's still in your queue. Please let us know what you find!


If `curl` can't connect, it means your Core node is no longer running. (Did you exit the Blockstack macOS app?)

---

If you are willing, could you also send us copies of the files `api_endpoint.log` and `queues.db` from the directory `/Users/larry/Library/Application Support/Blockstack/config/` (you'll have to replace `larry` with your username)?

You can PM them to me on Slack.

You'll also see a file `wallet.json` in the same directory, which, you guessed it, is your Core wallet! Please make a back up copy of this file. Combined with the password from earlier, we can use it to recover your name.

**Comment by danielmcclure** [comment]
After discussing on Slack I can confirm this was a local issue and not a bug. The Blockstack app wasn't open long enough to process the transactions after the confirmations came through.

I would suggest that there be some sort of warning message letting users know when they attempt to register an ID that they need to leave the app open for a certain amount of time to complete the registration. Perhaps a progress monitor would also add some clarity so people know things are happening for the four stages of; NAME_PREORDER, NAME_REGISTRATION, NAME_UPDATE, and NAME_TRANSFER.

**Comment by larrysalibra** [comment]
@danielmcclure great to hear! 

That's a great idea re a warning and registration status. I've opened an issue for that:  #369 

If your name successfully registered, can you close this issue?
