### ISSUE TITLE
Remove mixpanel code

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#410]
Centralized 3rd party tracking code doesn't really fit with our mission.

We also haven't been adding mixpanel events.

Propose we remove the code.

**Comment by pstan26** [comment]
counter: Propose we don't remove code. Just because we haven't setup events yet doesn't mean we won't, right? I also think this is much different from what we plan to do on the actual decentralized internet. If our goal is to increase the core interaction of the decentralized internet, this seems like something worth keeping so we have *some* data on converting people through the funnel.

**Comment by larrysalibra** [comment]
@pstan26 talking about the portal.
