### ISSUE TITLE
The user shouldn't be prompted for the core API password when going to localhost:8888 in incognito mode

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-portal#481]
This is the screen I see when I visit `localhost:8888`:

<img width="1525" alt="screen shot 2017-05-16 at 2 32 21 pm" src="https://cloud.githubusercontent.com/assets/994646/26122174/999b359c-3a44-11e7-92f4-dcc3eefa65e4.png">

Now, we have to figure out a way to load in the Core API password but we also can't show this screen. Let's brainstorm our options.

**Comment by larrysalibra** [comment]
They are also prompted for their core api password if they browse to the portal on a browser that isn't their default browser.

@shea256 Check out our earlier list: https://forum.blockstack.org/t/protecting-core-from-malicious-apps/911/5?u=larry

I suggest option 3, loading portal in a web view of our app.

**Comment by shea256** [comment]
OK can you explain option 3. Are you suggesting it operates completely outside of the browser in a desktop view?

**Comment by larrysalibra** [comment]
We decided to add a pairing option to pair your browser with blockstack.

**Comment by larrysalibra** [comment]
Fixed in #496 

<img width="488" alt="screen shot 2017-05-22 at 5 40 34 pm" src="https://cloud.githubusercontent.com/assets/597182/26332826/6ac0d3f2-3f27-11e7-82a5-3aa5f6a622bd.png">
<img width="492" alt="screen shot 2017-05-22 at 5 43 41 pm" src="https://cloud.githubusercontent.com/assets/597182/26332828/6c2bd390-3f27-11e7-9590-53a1c2edb414.png">
